# [tool.poetry]
# name = "territories"
# version = "0.0.1"
# description = "Manage territories."
# authors = ["Timo"]
# license = "MIT"
# readme = "README.md"

# [tool.poetry.dependencies]
# python = "^3.10"

# [tool.poetry.dev-dependencies]


# [tool.poetry.group.dev.dependencies]
# pytest = "^8.3.3"

# [build-system]
# requires = ["poetry-core>=1.0.0"]
# build-backend = "poetry.core.masonry.api"

[project]
name = "territories"
version = "0.0.1"
authors = [
  { name="Timo", email="author@example.com" },
]
description = "Manage territories."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"