[project]
name = "territories"
version = "0.0.2"
authors = [
  { name="Timo", email="author@example.com" },
]
description = "Manage territories."
readme = "README.md"
requires-python = ">=3.8"


dependencies = [
  "networkx"
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"