name: 'Run Unittest'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  contents: read
  pull-requests: read


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          # Optional - x64 or x86 architecture, defaults to x64
          # architecture: 'x64'

      - name: Install package
        run: |
          pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install .

      - name: Checks
        run: pip list

      - name: Test
        run: pytest

