name: 'Run Unittest'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  contents: read
  pull-requests: read


jobs:
  run-the-tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: create env
        run: python -m venv .venv && source .venv/bin/activate

      - name: Install package
        run: pip install -r requirements-dev.txt && pip install .

      - name: Check dir
        run: ls -la

      - name: Test
        run: pytest

