name: 'Run Unittest'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read


jobs:
  run-the-tests:
    # runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted", "staging-4c-16gb"]')[github.repository == 'github/docs-internal'] }}
    # runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: create env
        run: python -m venv .venv && source .venv/bin/activate

      - name: Install package
        run: pip install -r requirements-dev.txt && pip install .

      - name: Test
        run: pytest

