name: Upload Python Package

on:
  workflow_run:
    workflows: ["Run Tests"]  # Name of the first workflow
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/


  pypi-publish:
    runs-on: ubuntu-latest

    needs:
      - release-build

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write


    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        run: |
          echo "PYB_EXTRA_ARGS=publish upload" >> $GITHUB_ENV
          cat <<- EOF >~/.pypirc
          [distutils]
          index-servers=hedwige

          [hedwige]
          repository=http://pypi.hedwige.fr:8080
          username=${TWINE_USERNAME}
          password=${TWINE_PASSWORD}
          EOF
          chmod a+r ~/.pypirc

          python3 -m pip install --upgrade twine
          python3 -m twine upload dist/*
