name: Upload Python Package

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: read

jobs:
  pypi-publish:
    name: python
    runs-on: ubuntu-latest
    env:
      DEPLOY_BRANCHES: "refs/heads/main"
      UV_INDEX_DATAPOLITICS_USERNAME: datapolitics
      UV_INDEX_DATAPOLITICS_PASSWORD: ${{ secrets.PYPI_PSWD }}
      UV_PUBLISH_USERNAME: datapolitics
      UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_PSWD }}

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      # - name: Install the project
      #   run: uv sync --all-extras --dev

      # - name: Run tests
      #   run: uv run pytest

      - name: Upload package
        run: |
          uv build
          uv publish --index datapolitics
