name: Upload Python Package

on:    
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-build:
    if: github.event.workflow_run.conclusion == 'success'  # Run only if the first workflow succeeded
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/


  pypi-publish:
    runs-on: ubuntu-latest
    env:
      DEPLOY_BRANCHES: "refs/heads/main"
      TWINE_USERNAME: datapolitics
      TWINE_PASSWORD: ${{ secrets.PYPI_PSWD }}

    needs:
      - release-build

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        run: |
          python3 -m pip install --upgrade twine
          ls -la
          python3 -m twine upload --repository-url http://pypi.hedwige.fr:8080  dist/*
